services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./queries:/queries
      - ./data:/data

  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      AWS_ACCESS_KEY_ID: '' #! Insert AWS Access Key here to enable file writing to S3
      AWS_SECRET_ACCESS_KEY: '' #! Insert AWS Secret Key here to enable file writing to S3
    volumes:
      - .:/app

volumes:
  db_data: